language: node_js
dist: trusty
sudo: false # See https://docs.travis-ci.com/user/trusty-ci-environment/
group: beta
node_js:
  - "stable"
script:
  - npm test
  - npm i -g --production
  - splittable ./sample/lib/a ./sample/lib/b --write-to ./travis-out/
  - splittable -v
  - splittable -h
cache:
  directories:
  - node_modules
branches:
  only:
    - master
